// Date: 19.10.2014 07:49:30
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.ragingart.miningmodifications.client.renderer.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelCrank extends ModelBase
{
  //fields
    ModelRenderer Metal;
    ModelRenderer Stone;
    ModelRenderer Stick1;
    ModelRenderer Stick2;
  
  public ModelCrank()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      Metal = new ModelRenderer(this, 0, 0);
      Metal.addBox(-0.5F, -1F, -0.5F, 1, 1, 1);
      Metal.setRotationPoint(0F, 0F, 0F);
      Metal.setTextureSize(32, 32);
      Metal.mirror = true;
      setRotation(Metal, 0F, 0F, 0F);
      Stone = new ModelRenderer(this, 5, 0);
      Stone.addBox(-1F, -3F, -1F, 2, 2, 2);
      Stone.setRotationPoint(0F, 0F, 0F);
      Stone.setTextureSize(32, 32);
      Stone.mirror = true;
      setRotation(Stone, 0F, 0F, 0F);
      Stick1 = new ModelRenderer(this, 0, 8);
      Stick1.addBox(-0.5F, -6F, -0.5F, 1, 6, 1);
      Stick1.setRotationPoint(0F, -2F, 0F);
      Stick1.setTextureSize(32, 32);
      Stick1.mirror = true;
      setRotation(Stick1, 0.7853982F, 0.7853982F, 0F);
      Stick2 = new ModelRenderer(this, 0, 8);
      Stick2.addBox(-0.5F, -6F, -0.5F, 1, 6, 1);
      Stick2.setRotationPoint(0F, -2F, 0F);
      Stick2.setTextureSize(32, 32);
      Stick2.mirror = true;
      setRotation(Stick2, -0.7853982F, 0.7853982F, 0F);
  }
  
  public void render(int animProgress, float f)
  {
    float anim = (float)Math.PI/50.0F*animProgress;
    adjustRender(anim);
    Metal.render(f);
    Stone.render(f);
    Stick1.render(f);
    Stick2.render(f);
  }

  public void adjustRender(float anim){
      float eighthCake = 0.25F*(float)Math.PI;
      Metal.rotateAngleY = anim;
      Stone.rotateAngleY = anim;
      Stick1.rotateAngleY = eighthCake + anim;
      Stick2.rotateAngleY = eighthCake + anim;
  }

  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
