// Date: 20.10.2014 02:28:57
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.ragingart.miningmodifications.client.renderer.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import org.lwjgl.opengl.GL11;

public class ModelMultitool extends ModelBase
{
  //fields
    ModelRenderer Griff;
    ModelRenderer Kern;
    ModelRenderer Spitze;
    ModelRenderer Schutz1;
    ModelRenderer Schutz2;
    ModelRenderer Schutz3;
    ModelRenderer Schutz4;
    ModelRenderer Schutz5;
    ModelRenderer Schneide1A;
    ModelRenderer Schneide11;
    ModelRenderer Schneide12;
    ModelRenderer Schneide13;
    ModelRenderer Schneide14;
    ModelRenderer Schneide1E;
    ModelRenderer Schneide2A;
    ModelRenderer Schneide21;
    ModelRenderer Schneide22;
    ModelRenderer Schneide23;
    ModelRenderer Schneide24;
    ModelRenderer Schneide2E;
    ModelRenderer Schneide3A;
    ModelRenderer Schneide31;
    ModelRenderer Schneide32;
    ModelRenderer Schneide33;
    ModelRenderer Schneide34;
    ModelRenderer Schneide3E;
    ModelRenderer Schneide4A;
    ModelRenderer Schneide41;
    ModelRenderer Schneide42;
    ModelRenderer Schneide43;
    ModelRenderer Schneide44;
    ModelRenderer Schneide4E;
  
  public ModelMultitool()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Griff = new ModelRenderer(this, 0, 7);
      Griff.addBox(3F, -1F, -1F, 13, 2, 2);
      Griff.setRotationPoint(0F, 0F, 0F);
      Griff.setTextureSize(64, 32);
      Griff.mirror = true;
      setRotation(Griff, 0F, 0F, 0F);
      Kern = new ModelRenderer(this, 0, 11);
      Kern.addBox(16F, -1.5F, -1.5F, 11, 3, 3);
      Kern.setRotationPoint(0F, 0F, 0F);
      Kern.setTextureSize(64, 32);
      Kern.mirror = true;
      setRotation(Kern, 0.7853982F, 0F, 0F);
      Spitze = new ModelRenderer(this, 0, 0);
      Spitze.addBox(27F, -1F, -1F, 2, 2, 2);
      Spitze.setRotationPoint(0F, 0F, 0F);
      Spitze.setTextureSize(64, 32);
      Spitze.mirror = true;
      setRotation(Spitze, 0F, 0F, 0F);
      Schutz1 = new ModelRenderer(this, 36, 0);
      Schutz1.addBox(0.5F, -2F, -2F, 3, 4, 4);
      Schutz1.setRotationPoint(0F, 0F, 0F);
      Schutz1.setTextureSize(64, 32);
      Schutz1.mirror = true;
      setRotation(Schutz1, 0F, 0F, 0F);
      Schutz2 = new ModelRenderer(this, 20, 0);
      Schutz2.addBox(-0.5F, -1F, -1F, 1, 2, 2);
      Schutz2.setRotationPoint(0F, 0F, 0F);
      Schutz2.setTextureSize(64, 32);
      Schutz2.mirror = true;
      setRotation(Schutz2, 0F, 0F, 0F);
      Schutz3 = new ModelRenderer(this, 20, 0);
      Schutz3.addBox(15F, 1F, -1F, 1, 2, 2);
      Schutz3.setRotationPoint(0F, 0F, 0F);
      Schutz3.setTextureSize(64, 32);
      Schutz3.mirror = true;
      setRotation(Schutz3, 0F, 0F, 0F);
      Schutz4 = new ModelRenderer(this, 26, 0);
      Schutz4.addBox(3.5F, 2F, -2F, 1, 1, 4);
      Schutz4.setRotationPoint(0F, 0F, 0F);
      Schutz4.setTextureSize(64, 32);
      Schutz4.mirror = true;
      setRotation(Schutz4, 0F, 0F, 0F);
      Schutz5 = new ModelRenderer(this, 0, 4);
      Schutz5.addBox(4.25F, 3F, -1F, 11, 1, 2);
      Schutz5.setRotationPoint(0F, 0F, 0F);
      Schutz5.setTextureSize(64, 32);
      Schutz5.mirror = true;
      setRotation(Schutz5, 0F, 0F, 0F);
      Schneide1A = new ModelRenderer(this, 12, 0);
      Schneide1A.addBox(9.5F, -1F, -0.5F, 3, 2, 1);
      Schneide1A.setRotationPoint(16F, 0F, 0F);
      Schneide1A.setTextureSize(64, 32);
      Schneide1A.mirror = true;
      setRotation(Schneide1A, -0.418879F, 0F, 0.1570796F);
      Schneide11 = new ModelRenderer(this, 12, 0);
      Schneide11.addBox(8.4F, -1F, -1F, 3, 2, 1);
      Schneide11.setRotationPoint(16F, 0F, 0F);
      Schneide11.setTextureSize(64, 32);
      Schneide11.mirror = true;
      setRotation(Schneide11, -0.418879F, 0F, 0.3141593F);
      Schneide12 = new ModelRenderer(this, 12, 0);
      Schneide12.addBox(7.3F, -1F, -1.5F, 3, 2, 1);
      Schneide12.setRotationPoint(16F, 0F, 0F);
      Schneide12.setTextureSize(64, 32);
      Schneide12.mirror = true;
      setRotation(Schneide12, -0.418879F, 0F, 0.4712389F);
      Schneide13 = new ModelRenderer(this, 12, 0);
      Schneide13.addBox(6.2F, -1F, -2F, 3, 2, 1);
      Schneide13.setRotationPoint(16F, 0F, 0F);
      Schneide13.setTextureSize(64, 32);
      Schneide13.mirror = true;
      setRotation(Schneide13, -0.418879F, 0F, 0.6283185F);
      Schneide14 = new ModelRenderer(this, 12, 0);
      Schneide14.addBox(5.1F, -1F, -2.5F, 3, 2, 1);
      Schneide14.setRotationPoint(16F, 0F, 0F);
      Schneide14.setTextureSize(64, 32);
      Schneide14.mirror = true;
      setRotation(Schneide14, -0.418879F, 0F, 0.7853982F);
      Schneide1E = new ModelRenderer(this, 12, 0);
      Schneide1E.addBox(4F, -1F, -3F, 3, 2, 1);
      Schneide1E.setRotationPoint(16F, 0F, 0F);
      Schneide1E.setTextureSize(64, 32);
      Schneide1E.mirror = true;
      setRotation(Schneide1E, -0.418879F, 0F, 0.9424778F);
      Schneide2A = new ModelRenderer(this, 12, 0);
      Schneide2A.addBox(9.5F, -1F, -0.5F, 3, 2, 1);
      Schneide2A.setRotationPoint(16F, 0F, 0F);
      Schneide2A.setTextureSize(64, 32);
      Schneide2A.mirror = true;
      setRotation(Schneide2A, 2.722714F, 0F, -0.1570796F);
      Schneide21 = new ModelRenderer(this, 12, 0);
      Schneide21.addBox(8.4F, -1F, -1F, 3, 2, 1);
      Schneide21.setRotationPoint(16F, 0F, 0F);
      Schneide21.setTextureSize(64, 32);
      Schneide21.mirror = true;
      setRotation(Schneide21, 2.722714F, 0F, -0.3141593F);
      Schneide22 = new ModelRenderer(this, 12, 0);
      Schneide22.addBox(7.3F, -1F, -1.5F, 3, 2, 1);
      Schneide22.setRotationPoint(16F, 0F, 0F);
      Schneide22.setTextureSize(64, 32);
      Schneide22.mirror = true;
      setRotation(Schneide22, 2.722714F, 0F, -0.4712389F);
      Schneide23 = new ModelRenderer(this, 12, 0);
      Schneide23.addBox(6.2F, -1F, -2F, 3, 2, 1);
      Schneide23.setRotationPoint(16F, 0F, 0F);
      Schneide23.setTextureSize(64, 32);
      Schneide23.mirror = true;
      setRotation(Schneide23, 2.722714F, 0F, -0.6283185F);
      Schneide24 = new ModelRenderer(this, 12, 0);
      Schneide24.addBox(5.1F, -1F, -2.5F, 3, 2, 1);
      Schneide24.setRotationPoint(16F, 0F, 0F);
      Schneide24.setTextureSize(64, 32);
      Schneide24.mirror = true;
      setRotation(Schneide24, 2.722714F, 0F, -0.7853982F);
      Schneide2E = new ModelRenderer(this, 12, 0);
      Schneide2E.addBox(4F, -1F, -3F, 3, 2, 1);
      Schneide2E.setRotationPoint(16F, 0F, 0F);
      Schneide2E.setTextureSize(64, 32);
      Schneide2E.mirror = true;
      setRotation(Schneide2E, 2.722714F, 0F, -0.9424778F);
      Schneide3A = new ModelRenderer(this, 12, 0);
      Schneide3A.addBox(9.5F, -1F, -0.5F, 3, 2, 1);
      Schneide3A.setRotationPoint(16F, 0F, 0F);
      Schneide3A.setTextureSize(64, 32);
      Schneide3A.mirror = true;
      setRotation(Schneide3A, -1.989675F, 0.1570796F, 0F);
      Schneide31 = new ModelRenderer(this, 12, 0);
      Schneide31.addBox(8.4F, -1F, -1F, 3, 2, 1);
      Schneide31.setRotationPoint(16F, 0F, 0F);
      Schneide31.setTextureSize(64, 32);
      Schneide31.mirror = true;
      setRotation(Schneide31, -1.989675F, 0.3141593F, 0F);
      Schneide32 = new ModelRenderer(this, 12, 0);
      Schneide32.addBox(7.3F, -1F, -1.5F, 3, 2, 1);
      Schneide32.setRotationPoint(16F, 0F, 0F);
      Schneide32.setTextureSize(64, 32);
      Schneide32.mirror = true;
      setRotation(Schneide32, -1.989675F, 0.4712389F, 0F);
      Schneide33 = new ModelRenderer(this, 12, 0);
      Schneide33.addBox(6.2F, -1F, -2F, 3, 2, 1);
      Schneide33.setRotationPoint(16F, 0F, 0F);
      Schneide33.setTextureSize(64, 32);
      Schneide33.mirror = true;
      setRotation(Schneide33, -1.989675F, 0.6283185F, 0F);
      Schneide34 = new ModelRenderer(this, 12, 0);
      Schneide34.addBox(5.1F, -1F, -2.5F, 3, 2, 1);
      Schneide34.setRotationPoint(16F, 0F, 0F);
      Schneide34.setTextureSize(64, 32);
      Schneide34.mirror = true;
      setRotation(Schneide34, -1.989675F, 0.7853982F, 0F);
      Schneide3E = new ModelRenderer(this, 12, 0);
      Schneide3E.addBox(4F, -1F, -3F, 3, 2, 1);
      Schneide3E.setRotationPoint(16F, 0F, 0F);
      Schneide3E.setTextureSize(64, 32);
      Schneide3E.mirror = true;
      setRotation(Schneide3E, -1.989675F, 0.9424778F, 0F);
      Schneide4A = new ModelRenderer(this, 12, 0);
      Schneide4A.addBox(9.5F, -1F, -0.5F, 3, 2, 1);
      Schneide4A.setRotationPoint(16F, 0F, 0F);
      Schneide4A.setTextureSize(64, 32);
      Schneide4A.mirror = true;
      setRotation(Schneide4A, 1.151917F, -0.1570796F, 0F);
      Schneide41 = new ModelRenderer(this, 12, 0);
      Schneide41.addBox(8.4F, -1F, -1F, 3, 2, 1);
      Schneide41.setRotationPoint(16F, 0F, 0F);
      Schneide41.setTextureSize(64, 32);
      Schneide41.mirror = true;
      setRotation(Schneide41, 1.151917F, -0.3141593F, 0F);
      Schneide42 = new ModelRenderer(this, 12, 0);
      Schneide42.addBox(7.3F, -1F, -1.5F, 3, 2, 1);
      Schneide42.setRotationPoint(16F, 0F, 0F);
      Schneide42.setTextureSize(64, 32);
      Schneide42.mirror = true;
      setRotation(Schneide42, 1.151917F, -0.4712389F, 0F);
      Schneide43 = new ModelRenderer(this, 12, 0);
      Schneide43.addBox(6.2F, -1F, -2F, 3, 2, 1);
      Schneide43.setRotationPoint(16F, 0F, 0F);
      Schneide43.setTextureSize(64, 32);
      Schneide43.mirror = true;
      setRotation(Schneide43, 1.151917F, -0.6283185F, 0F);
      Schneide44 = new ModelRenderer(this, 12, 0);
      Schneide44.addBox(5.1F, -1F, -2.5F, 3, 2, 1);
      Schneide44.setRotationPoint(16F, 0F, 0F);
      Schneide44.setTextureSize(64, 32);
      Schneide44.mirror = true;
      setRotation(Schneide44, 1.151917F, -0.7853982F, 0F);
      Schneide4E = new ModelRenderer(this, 12, 0);
      Schneide4E.addBox(4F, -1F, -3F, 3, 2, 1);
      Schneide4E.setRotationPoint(16F, 0F, 0F);
      Schneide4E.setTextureSize(64, 32);
      Schneide4E.mirror = true;
      setRotation(Schneide4E, 1.151917F, -0.9424778F, 0F);
  }
  
  public void render(float f,float anim)
  {
    Griff.render(f);
    Schutz1.render(f);
    Schutz2.render(f);
    Schutz3.render(f);
    Schutz4.render(f);
    Schutz5.render(f);
    GL11.glRotatef(anim, 1.0F, 0.0F, 0.0F);
    Kern.render(f);
    Spitze.render(f);
    Schneide1A.render(f);
    Schneide11.render(f);
    Schneide12.render(f);
    Schneide13.render(f);
    Schneide14.render(f);
    Schneide1E.render(f);
    Schneide2A.render(f);
    Schneide21.render(f);
    Schneide22.render(f);
    Schneide23.render(f);
    Schneide24.render(f);
    Schneide2E.render(f);
    Schneide3A.render(f);
    Schneide31.render(f);
    Schneide32.render(f);
    Schneide33.render(f);
    Schneide34.render(f);
    Schneide3E.render(f);
    Schneide4A.render(f);
    Schneide41.render(f);
    Schneide42.render(f);
    Schneide43.render(f);
    Schneide44.render(f);
    Schneide4E.render(f);
    GL11.glRotatef(anim, -1.0F, 0.0F, 0.0F);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
