// Date: 26.09.2014 03:14:26
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.ragingart.maatsmod.client.renderer.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelPlatformExt extends ModelBase
{
  //fields
  public ModelRenderer Shape1;
  public ModelRenderer Shape2;
  public ModelRenderer Shape3;
  public ModelRenderer Shape4;
  
  public ModelPlatformExt()
  {
    textureWidth = 128;
    textureHeight = 50;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(-16F, 0F, -16F, 32, 0, 32);
      Shape1.setRotationPoint(0F, 0F, 0F);
      Shape1.setTextureSize(128,32);
      Shape1.mirror = false;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 34);
      Shape2.addBox(-2F, 1F, -2F, 4, 3, 4);
      Shape2.setRotationPoint(0F, 0F, 0F);
      Shape2.setTextureSize(128, 50);
      Shape2.mirror = false;
      setRotation(Shape2, 0F, 0F, 0F);
      /*
      Shape3 = new ModelRenderer(this, 20, 34);
      Shape3.addBox(-0.5F, 3F, -1.5F, 1, 7, 1);
      Shape3.setRotationPoint(0F, 0F, 0F);
      Shape3.setTextureSize(128, 50);
      Shape3.mirror = false;
      setRotation(Shape3, 0.7853982F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 30, 34);
      Shape4.addBox(-2F, 7F, 6F, 4, 2, 2);
      Shape4.setRotationPoint(0F, 0F, 0F);
      Shape4.setTextureSize(128, 50);
      Shape4.mirror = false;
      setRotation(Shape4, 0F, 0F, 0F);
      */
  }

  public void render(float f,float rotHelper)
  {
    Shape1.render(f);
    /*
    Shape2.render(f);

    GL11.glRotatef(rotHelper,0,1,0);
      for (int i = 0; i < 4; i++) {
          Shape3.render(f);
          Shape4.render(f);
          GL11.glRotatef(90,0,1,0);
      }
    */
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
}
